### ISSUE TITLE
Work failed in line `is_new_file = args.is_new_file[file_name]`

### ISSUE THREAD

**Issue by leeebo** [espressif/check-copyright#12]
The `check-copyright` works for me weeks ago, but currently we found the CI running always fail with：

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/libo/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/check_copyright.py", line 722, in <module>
    main()
  File "/home/libo/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/check_copyright.py", line 684, in main
    wrong_header_files, modified_files, must_be_updated = check_copyrights(args, config)
  File "/home/libo/.espressif/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/check_copyright.py", line 511, in check_copyrights
    is_new_file = args.is_new_file[file_name]
KeyError: './examples/camera/video_recorder/components/avi_video_process/avi_def.h'
```

**Run follow command in [esp-iot-solution](https://github.com/espressif/esp-iot-solution) repo to reproduce the bug:**

```python
python -m check_copyright --verbose --dry-run --ignore tools/ci/ignore_list_copyright.txt --config tools/ci/check_copyright_config.yaml .
```

Please help to analyze the root of the problem.

**Comment by leeebo** [comment]
Specify the install version to `v1.0.3` can fix.

**Comment by fhrbata** [comment]
Hello @leeebo ,

thank you for the report. It seems that
 `is_new_file = args.is_new_file[file_name]`
should actually be 
`is_new_file = args.is_new_file(file_name)`

The dict contains just newly added files, not all that are modified.

**Comment by sudeep-mohanty** [comment]
Thanks for reporting this @leeebo. Looks like the update I made didn't take into account that the `check_copyright.py` script can be run standalone on a repository with no files in the git staging area. Will make a fix for this.

**Comment by leeebo** [comment]
@sudeep-mohanty @fhrbata The latest fix https://github.com/espressif/check-copyright/pull/13 works for me now, thanks!
